// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxsLMChb3G5u8pIhdvCZXqJWiLf0GGIvM',
    appId: '1:439695908738:web:e55ef9b4e17ac31335799b',
    messagingSenderId: '439695908738',
    projectId: 'bitex-7b207',
    authDomain: 'bitex-7b207.firebaseapp.com',
    storageBucket: 'bitex-7b207.firebasestorage.app',
    measurementId: 'G-LXP1D17EF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuWFV4SEpQp6QjASKVz0fCRmZUFXLpxro',
    appId: '1:439695908738:android:9b33ea02fc25c25435799b',
    messagingSenderId: '439695908738',
    projectId: 'bitex-7b207',
    storageBucket: 'bitex-7b207.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4qHiPK7N-oCf9QbPH0BnhYHAp_E22Zrs',
    appId: '1:439695908738:ios:428ee98137897a0435799b',
    messagingSenderId: '439695908738',
    projectId: 'bitex-7b207',
    storageBucket: 'bitex-7b207.firebasestorage.app',
    iosBundleId: 'com.example.bikex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4qHiPK7N-oCf9QbPH0BnhYHAp_E22Zrs',
    appId: '1:439695908738:ios:428ee98137897a0435799b',
    messagingSenderId: '439695908738',
    projectId: 'bitex-7b207',
    storageBucket: 'bitex-7b207.firebasestorage.app',
    iosBundleId: 'com.example.bikex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxsLMChb3G5u8pIhdvCZXqJWiLf0GGIvM',
    appId: '1:439695908738:web:b2f53b2a7d02098c35799b',
    messagingSenderId: '439695908738',
    projectId: 'bitex-7b207',
    authDomain: 'bitex-7b207.firebaseapp.com',
    storageBucket: 'bitex-7b207.firebasestorage.app',
    measurementId: 'G-478WG9340N',
  );
}
